name: Build & Test

on: [ push, pull_request, workflow_call ]

jobs:
  check_linux:
    name: Performing Linux Build / Update
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Preparing Cache..
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-

      - name: Running Tests
        run: cargo check --all-features

      - name: Checking Formatting
        run: cargo fmt --all -- --check

      - name: Performing Clippy Test
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Setting up Git for Code Generation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setting up Python
        run: |
          pip install flatpak-cargo-generator

      - name: Generating file
        run: |
          flatpak-cargo-generator Cargo.lock -o generated-sources.json

      - name: Check for Changes and Update
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git add generated-sources.json
            git commit -m "chore: update flatpak sources"
            git push
          fi        
        
