name: Build & Test

on: [ push, pull_request, workflow_call ]

jobs:
  check_linux:
    name: Performing Linux Build / Update
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Preparing Cache..
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-

      - name: Running Tests
        run: cargo check --all-features

      - name: Checking Formatting
        run: cargo fmt --all -- --check

      - name: Performing Clippy Test
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Dispatch Flatpak Updater
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CROSS_REPO_DISPATCH_TOKEN }}  # Stored in the org secrets
          repository: beacn-on-linux/beacn-utility-flatpak
          event-type: update-generated-sources